# Generated by Django 4.2.2 on 2023-06-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_001', '0002_rename_user_id_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
